### PR TITLE
Chapter2

### PR DESCRIPTION
**Pull request by AjanShrestha**
- We set out to develop the basic framework for our game.
- We started by defining and implementing a splash screen and game menu. 
- We then created a simple level system and an asset loader to dynamically load the images used by each level. 
- We set up the game canvas and animation loop and implemented parallax scrolling to give the illusion of depth. 
- We captured and used mouse events to let the player pan around the level.
- At this point we have a basic game world that we can interact with, so we are ready to add the various game entities and game physics.

### CODE REVIEW

**Review by AjanShrestha — COMMENTED** [review]
All Good!

**Comment by James-Ndaka** [comment]
There is a part of your code that I tried but could not function. What you have written in your book and what you have in here are conflicting a little bit. (Am a beginner in developing games)

**Comment by AjanShrestha** [comment]
> There is a part of your code that I tried but could not function. What you have written in your book and what you have in here are conflicting a little bit. (Am a beginner in developing games)

Hi @James-Ndaka, Good to know that you are into developing games. 

One thing I want to point out is that I am not the author of the book. I just followed the book written by Shankar, Aditya Ravi. Here, is the link to the book [Pro HTML5 Games](https://www.apress.com/in/book/9781484229095)

Are you stuck with the screen just scrolling to the left? If so, I have also completed till that section.I stopped the progress there because I also got felt it didn't function the way it should.

**Comment by James-Ndaka** [comment]
Thank you @AjanShrestha for your response. It has given me headaches. There is a part of javascript code that is not working properly.

**Comment by James-Ndaka** [comment]
What are you working on right now

**Comment by AjanShrestha** [comment]
> What are you working on right now

Hey @James-Ndaka 
I am currently exploring Go.
What are you working on at the moment?

**Pull request merged**
